
 exec-once = nm-applet &
 exec-once = waybar &  
exec-once = swww-daemon

exec-once = sleep 2 && swww img /home/archimi/wallpaper/a2.png # your wall  


exec-once = mako
exec-once = notify-send "Hyprland" "WElCOME YOUR NAME ❤ᶻ 𝗓 𐰁" -t 10000


exec-once = [workspace 3  silent] discord
exec-once = swww-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


